# Required metadata
sonar.projectKey=my-spring-boot-app-30-Mar-2026
sonar.projectName=Spring Boot App-30-Mar-2026
sonar.projectVersion=1.0
##

# Source code location (use full relative path from repo root)
sonar.sources=src

# Compiled classes (binaries)
sonar.java.binaries=target/classes

# Encoding
sonar.sourceEncoding=UTF-8
