apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  labels:
    app: spring-boot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: spring-boot-app
        image: 076226033208.dkr.ecr.ap-south-1.amazonaws.com/springboot-java-app:1a2cee8b72efb89da255d4c7c7c65bcca82beffe
        ports:
        - containerPort: 8080
          #ismail
